sudo: required
services:
    - docker

before_install:
    - docker build -t calkines/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true calkines/react-test npm test

after_success:
    #build stage
    - docker build -t calkines/multi-client ./client
    - docker build -t calkines/multi-nginx ./nginx
    - docker build -t calkines/multi-server ./server
    - docker build -t calkines/multi-worker ./worker    
    #login in docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #pushes image
    - docker push calkines/multi-client
    - docker push calkines/multi-server
    - docker push calkines/multi-nginx 
    - docker push calkines/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-567347929550
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
